export const FETCH_ISSUES_REQUEST = 'FETCH_ISSUES_REQUEST';
export const FETCH_ISSUES_SUCCESS = 'FETCH_ISSUES_SUCCESS';
export const FETCH_ISSUES_FAILURE = 'FETCH_ISSUES_FAILURE';

export const FETCH_REPOINFO_REQUEST = 'FETCH_REPOINFO_REQUEST';
export const FETCH_REPOINFO_SUCCESS = 'FETCH_REPOINFO_SUCCESS';
export const FETCH_REPOINFO_FAILURE = 'FETCH_REPOINFO_FAILURE';
